namespace Clockwork
{
  public enum STATISTIC
  {
    STOCKPRODUCED = 0,
    STOCKSENT = 1,
    STOCKLOST = 2,
    STOCKDELIVERED = 3,
    STOCKDELIVEREDUSED = 4,
    STOCKDELIVEREDLOST = 5,
    PRODUCTPRODUCED = 6,
    PRODUCTPRODUCEDUSED = 7,
    PRODUCTPRODUCEDLOST = 8,
    PRODUCTDELIVERED = 9
  }
}
